Parapothek/Parapothek/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('core.urls')),
    path('fast/',include ('fastsearch.urls')),
    path('fichas/',include('fichas.urls')),
    
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Parapothek/core/urls.py
from django.urls import path
from core import views





urlpatterns = [
    
    path("", views.home , name="portada"),
    
]

Parapothek/fichas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path modelo ficha
    path('fichas/',FichasViews.as_view(), name= 'fichas'),
    path('fichaupdate/<int:pk>',FichaUpdate.as_view(),name='fichaupdate'),
    path('buscarficha',buscadorfichas,name='buscarficha'),
    path('fichaspuntuacion/',FichasViewsPuntuacion.as_view(), name= 'fichaspuntuacion'),
    #path añadir indicaciones
    path('fichas/indicaciones/<int:pk>',views.indicacioneschoose, name= 'indicacioneschoose'),
    #path modelo zona
    path('zonasaplicacion/',ZonasViews.as_view(),name='zonas'),
    path('zonacreate/',ZonaCreate.as_view(), name= 'zonacreate'),
    path('zonaupdate/<int:pk>',ZonaUpdate.as_view(),name='zonaupdate'),
    path('zonadelete/<int:pk>',ZonaDelete.as_view(),name='zonadelete'),
    #path modelo indicaciones
    path('indicaciones/',IndicacionesViews.as_view(),name='indicaciones'),
    path('indicacioncreate/',IndicacionCreate.as_view(), name= 'indicacioncreate'),
    path('indicacionupdate/<int:pk>',IndicacionUpdate.as_view(),name='indicacionupdate'),
    path('indicaciondelete/<int:pk>',IndicacionDelete.as_view(),name='indicaciondelete'),
    #path puntuar
    path ('fichas/puntuar/<int:id>', views.puntuar,name='puntuar')
    
    
]
    

Parapothek/fichas/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

    


class Inventario(models.Model):
    
    id = models.AutoField(primary_key=True,unique=True)
    cn = models.TextField(blank=True, null=True)
    nombre = models.TextField(blank=True, null=True)
    pvf = models.TextField(blank=True, null=True)
    pvp = models.TextField(blank=True, null=True)
    stock = models.IntegerField(blank=True, null=True)
    zonap = models.ForeignKey ('fichas.Zona',verbose_name='Zona de aplicación',on_delete=models.SET_NULL,null=True,blank=True)
    indicaciones = models.ManyToManyField('fichas.Indicacion',blank=True, related_name="indicacionlist")
    puntuacion = models.ManyToManyField('fichas.Puntuar',blank=True)
    media = models.DecimalField(max_digits=4,decimal_places=2,null=True,blank=True)

    def __str__(self):
        return self.nombre 
    
    class Meta:
        managed = True
        db_table = 'Inventario'
        
    def save(self, *args, **kwargs):
        listanotas=[]
        if self.puntuacion.all():
            for puntuacion in self.puntuacion.all():
                listanotas.append(puntuacion.nota)
            
            mediatotal= sum(listanotas)/len(listanotas)
            self.media=round(mediatotal,2)
            super().save(*args, **kwargs)
        else:
         super().save(*args, **kwargs)
            
        
            
    
        

    
    
    
    
def zona_upload_to(instance, filename):
    old_instance = Zona.objects.get(pk=instance.pk)
    old_instance.image.delete()
    return 'zonas/' + filename   

class Zona(models.Model):
    nombre= models.CharField(max_length=30)
    image= models.ImageField(upload_to=zona_upload_to,blank=True, null=True)
    
    def __str__(self):
        return self.nombre
    class Meta:
        managed = True
        app_label='fichas'
        ordering= ('nombre',)

class Indicacion(models.Model):
    nombre= models.CharField(max_length=40)
    zona= models.ManyToManyField('fichas.Zona')
    def __str__(self):
        return self.nombre
    class Meta:
        managed = True
        app_label='fichas' 
        ordering= ('nombre',)
   
    
class Puntuar(models.Model):
    dni=models.CharField(max_length=9,blank=True,null=True,help_text='12345678A')
    nota=models.DecimalField(max_digits=4,decimal_places=2)
    fecha=models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return  '({}) {}/{}/{}'.format(self.dni,self.fecha.day, self.fecha.month, self.fecha.year)

Parapothek/fichas/forms.py
from django import forms
from django.forms import CheckboxSelectMultiple, TextInput
from django.core.exceptions import ValidationError

from .models import Inventario,Puntuar,Indicacion


        

class PuntuarForm(forms.ModelForm):
    class Meta:
        model = Puntuar
        fields = '__all__'
        
class InventarioIndicacionesForm(forms.ModelForm):
        
        class Meta:
            model = Inventario
            fields = ('indicaciones',)
            widgets = {
            'indicaciones': CheckboxSelectMultiple,}

class IndicacionesForm(forms.ModelForm):
     
    class Meta:
        model = Indicacion
        fields = ('__all__')
        widgets = {
            'nombre':forms.TextInput,
            'zona': forms.CheckboxSelectMultiple,
        }            

Parapothek/fichas/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import views
from .models import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator



# Create your views here.
@login_required(login_url='admin:login')
def buscadorfichas(request):
    if request.method=='POST':
        data=request.POST.get("buscar")
        objectlist=Inventario.objects.filter(nombre__icontains=data)| Inventario.objects.filter(cn__icontains=data)
        return render(request,"fichas/buscadorfichas.html",{'objectlist':objectlist,})
    else:
        objectlist=Inventario.objects.all()
        return render(request,"fichas/buscadorfichas.html",{'objectlist':objectlist,}) 
    


#-----------------Modelo ficha-------------------------------
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class FichasViews(ListView):
    model = Inventario
    template_name = "fichas/fichas.html"
    paginate_by = 30
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class FichasViewsPuntuacion(ListView):
    model = Inventario
    template_name = "fichas/fichaspuntuacion.html"
    

    def get_queryset(self):
        fichaspuntuadas=[]
        fichas= Inventario.objects.filter(media__gte=7).order_by('-media')
        
       
        
        self.queryset = fichas
        return self.queryset

@method_decorator(login_required(login_url='admin:login'), name='dispatch')    
class FichaUpdate(UpdateView):
    model = Inventario
    template_name = "fichas/editarficha.html"
    fields= ('zonap',)
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        listapuntuaciones = []
        
        puntuaciones= self.object.puntuacion.all()
        for puntuacion in puntuaciones:
            listapuntuaciones.append(puntuacion.nota)
        if len(listapuntuaciones)== 0:
            votos=0
            imagen='core/assets/img/0stars.png'
            context['votos']=votos
            context['imagen']=imagen
            return context
        else:
            if self.object.media is None:
                imagen='core/assets/img/0stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
            
            elif self.object.media >= 9.51:
                imagen='core/assets/img/5stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
                
            elif self.object.media > 7.51 and self.object.media <=9.50 : 
                imagen='core/assets/img/4stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context 
            elif self.object.media > 5.50 and self.object.media <=7.50 :  
                imagen='core/assets/img/3stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
            elif self.object.media > 3.51 and self.object.media <=5.50 :   
                imagen='core/assets/img/2stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
            elif self.object.media > 1.51 and self.object.media <=3.50:
                imagen='core/assets/img/1stars.png.jpg'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
            else:
                imagen='core/assets/img/0stars.png'
                votos=len(listapuntuaciones)
                context['votos']=votos
                context['imagen']=imagen
                return context
   
    def get_success_url(self):
        return reverse_lazy('fichaupdate', args=[self.object.id]) + '?ok'




#-----------------Modelo ZonaAplicacion---------------------------------------------------------------------

# Ver lista Zonas de aplicación:
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class ZonasViews(ListView):
    model = Zona
    template_name = "fichas/zonasaplicacion.html"

#Crear zona de aplicación
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class ZonaCreate(CreateView):
    template_name = "fichas/crearzona.html"
    model = Zona
    fields = "__all__"
    def get_success_url(self):
        return reverse_lazy('zonacreate') + '?ok'

# Editar ZonaAplicaion
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class ZonaUpdate(UpdateView):
    model = Zona
    template_name = "fichas/editarzona.html"
    fields ="__all__"
    def get_success_url(self):
        return reverse_lazy('zonaupdate', args=[self.object.id]) + '?ok'

# Borrar Zona de Aplicación
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class ZonaDelete(DeleteView):
    model = Zona
    template_name = "fichas/borrarzona.html"
    success_url = reverse_lazy('zonas')


#-----------------Modelo Indicaciones---------------------------------------------------------------------
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class IndicacionesViews(ListView):
    model = Indicacion
    template_name = "fichas/indicaciones.html"
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class IndicacionCreate(CreateView):
    template_name = "fichas/crearindicacion.html"
    model = Indicacion
    form_class = IndicacionesForm
    def get_success_url(self):
        return reverse_lazy('indicacioncreate') + '?ok'
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class IndicacionUpdate(UpdateView):
    model = Indicacion
    template_name = "fichas/editarindicacion.html"
    form_class = IndicacionesForm
    def get_success_url(self):
        return reverse_lazy('indicacionupdate', args=[self.object.id]) + '?ok'
@method_decorator(login_required(login_url='admin:login'), name='dispatch')
class IndicacionDelete(DeleteView):
    model = Indicacion
    template_name = "fichas/borrarindicacion.html"
    success_url = reverse_lazy('indicaciones')
@login_required(login_url='admin:login')
def puntuar(request,id,*args,**kwargs):
    fichaid= id
    
    ficha= Inventario.objects.get(id=fichaid) #ya tenemos el objeto para la foreign key.
    from .forms import PuntuarForm
    form = PuntuarForm()
    nombre= ficha.nombre


    if request.method=='POST':
        dni= request.POST ['dni']
        nota= request.POST ['nota']
        from .models import Puntuar
        
        if len(dni)== 9 and float(nota) <= 10:
            comprobante=0
            a=Puntuar.objects.create(dni=dni,nota=nota)
            for puntuacion in ficha.puntuacion.all():
                if puntuacion.dni == a.dni:
                    comprobante += 1
                

            if comprobante == 0:
                a.save()
                ficha.puntuacion.add(a)
                ficha.save()
                listanotas=[]
                for nota in ficha.puntuacion.all():
                    listanotas.append(nota.nota)
                
               
                
                respuesta1='Nueva puntuacion añadida!!!!!!'
                
                return render(request,"fichas/puntuar.html",{'nombre':nombre,"respuesta1":respuesta1,'fichaid':fichaid,'form':form,})



            else:
                respuesta2=' {} ya ha votado anteriormente este producto!!!'.format(dni)
                return render(request,"fichas/puntuar.html",{'nombre':nombre,"respuesta2":respuesta2,'fichaid':fichaid,'form':form})
        
        else:
            respuesta2= 'Error al introducir los datos'
            return render(request,"fichas/puntuar.html",{'nombre':nombre,'form':form,'respuesta2':respuesta2,'fichaid':fichaid})
            
            
    return render(request,"fichas/puntuar.html",{'nombre':nombre,'form':form,'fichaid':fichaid})

@login_required(login_url='admin:login')
def indicacioneschoose(request,*args,**kwargs):
    from .models import Inventario,Indicacion
    from .forms import InventarioIndicacionesForm
    fichapk= kwargs['pk']
    ficha= Inventario.objects.get( pk=fichapk ) #ficha seleccionada. ahora hay que seleccionar la zona.
    zona= ficha.zonap
    indicaciones=Indicacion.objects.filter(zona=zona)
    form=InventarioIndicacionesForm(instance=ficha)
    form.fields["indicaciones"].queryset = indicaciones
    if request.method == "POST":
        form=InventarioIndicacionesForm(request.POST)
        
        if form.is_valid():
            respuesta='Indicaciones incluidas'

            for indicacion in form.cleaned_data['indicaciones']:
                ficha.indicaciones.add(indicacion)
                ficha.save()
            form.fields["indicaciones"].queryset = indicaciones
            
            
            
            
            
            
            return render(request,"fichas/indicacioneschoose.html",{'ficha':ficha,'respuesta':respuesta,'form':form,'fichaid':fichapk})
        else:
            respuesta='Error en el formulario!'
            return render(request,"fichas/indicacioneschoose.html",{'ficha':ficha,'respuesta':respuesta,'form':form,'fichaid':fichapk})
    respuesta=''
    return render(request,"fichas/indicacioneschoose.html",{'ficha':ficha,'form':form,'respuesta':respuesta,'fichaid':fichapk})

    

Parapothek/fichas/templates/fichas/borrarindicacion.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}

<br>
<br>
<br>
<br>


<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
                <input type="submit" value="Sí, borrar esta indicación" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

Parapothek/fichas/templates/fichas/borrarzona.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}

<br>
<br>
<br>
<br>
<h3>ATENCIÓN</h3>
<p><ins>Si borra esta zona de aplicación, se borraran automáticamente los artículos que se apliquen en {{object}}.!!!!</ins></p>

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
                <input type="submit" value="Sí, borrar zona de aplicación" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

Parapothek/fichas/templates/fichas/buscadorfichas.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}
<br>
<br>
<style>
table{
  margin:auto;
  padding:15px;
  width:80%;
}
td{
  padding:5px;
  text-align:left;
}
tr{
  padding:10px
}
</style>


 

<h2> <int>Fichas Disponibles</int></h2>

<form method="POST" action={%url 'buscarficha'%}>{% csrf_token %}
  <table style="float:right; margin-right:50px; width:10%">
    <tr>

      <td>
      <input style="height: 30px;" type="text" name="buscar"></td>
      <td><input type="submit" value="Buscar"></td>
<br>
<br>
<br>

<table>

    {%for ficha in objectlist %}
    <tr>    
        
    
    <td>CN: {{ficha.cn}}</td>   
    <td>Nombre: <a href="{%url 'fichaupdate' ficha.pk%}"><b>{{ficha.nombre}} </b></a></td> 
    <td>Zona: {{ficha.zonap}}</td>   
    <td>PVP: {{ficha.pvp}}</td>   
    <td>PVF: {{ficha.pvf}}</td>   
    <td>Stock: {{ficha.stock}} </td>      
    <td><a href="{%url 'fichaupdate' ficha.pk%}"title="Editar" ><i class="fa fa-edit"> </i></a></td>
        
        
     </tr>   
    {%endfor%}
</table>
<!-- Menú de paginación -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
</div>
</div>
</div>
</main>
{%endblock%}

Parapothek/fichas/templates/fichas/crearindicacion.html
{%extends 'core/portada.html'%}
{% load static %}



{% block content %}
<br>
<br>
<h2>Crear una indicacion</h2>
{%if 'ok' in request.GET %}
<p style="color:rgb(11, 146, 11) ">Indicación creada correctamente.!!!!</p>
{%endif%}

<br>
<br>
<div id='formulario'>
<form method="post" style='display: inline-block;'>{% csrf_token %}
<div id 'nombreindicacion'>
{{ form.nombre.errors }}
<p><label for="{{ form.nombre.id_for_label }}">Nombre: </label></p>
{{form.nombre}}
</div>
<br>
<div id='zonaindicacion'>
{{form.zona.errors}}
<p><label for="{{ form.zona.id_for_label }}">Zona: </label></p>
<div id='zonascheck' style="height: 15em; width: auto; overflow: auto; text-align: left;">{%for indicacion in form.zona %}
<div>{{indicacion}}</div>
{%endfor%}</div>
</div>

</div>




    
<br>
<input type="submit" value="Crear indicación" />
</form>
</div>
{% endblock %}

Parapothek/fichas/templates/fichas/crearzona.html
{%extends 'core/portada.html'%}
{% load static %}



{% block content %}
<br>
<br>
<h1>Crear una zona de aplicación</h1>
{%if 'ok' in request.GET %}
<p style="color:rgb(11, 146, 11) ">Zona creada correctamente.!!!!</p>
{%endif%}
<h5>Recomendaciones:</h5>
<p>La zona de aplicación creada se podrá seleccionar en las opciones de crear una nueva ficha. 
 A cada artículo solo se le podrá seleccionar una única zona de aplicación
</p>
<br>
<br>
<!--Para que el formulario acepte imagenes, hay que poner el enctype-->
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    
    <br>
    <br>
    
    <input type="submit" value="Crear zona" />
</form>


{% endblock %}

Parapothek/fichas/templates/fichas/fichas.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}
<br>
<br>
<style>
table{
  margin:auto;
  padding:15px;
  width:80%;
}
td{
  padding:5px;
  text-align:left;
}
tr{
  padding:10px
}

</style>


 

<h2> <int>Fichas Disponibles</int></h2>

<form method="POST" action={%url 'buscarficha'%}>{% csrf_token %}
  <table style="float:right; margin-right:50px; width:10%">
    <tr>

      <td>
      <input style="height: 30px;" type="text" name="buscar"></td>
      <td><input type="submit" value="Buscar"></td>

  </table>
</form>
<br>
<br>
<br>

<table>

    {%for ficha in inventario_list %}
    <tr>    
        
    
    <td>CN: {{ficha.cn}}</td>   
    <td>Nombre: <a href="{%url 'fichaupdate' ficha.pk %}"><b>{{ficha.nombre}} </b></a></td> 
    <td>Zona: {{ficha.zonap}}</td>
    <td>PVP: {{ficha.pvp}}</td>   
    <td>PVF: {{ficha.pvf}}</td>
    <td>Puntuación: <b><id style="font-size: 13px; color:green;">{{ficha.media}}</id></b></td>   
    <td>Stock: {{ficha.stock}} </td> 
       
    <td><a href="{%url 'fichaupdate' ficha.id%}"title="Editar" ><i class="fa fa-edit"> </i></a></td>
        
        
     </tr>   
    {%endfor%}
</table>
<!-- Menú de paginación -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
</div>
</div>
</div>
</main>
{%endblock%}

Parapothek/fichas/templates/fichas/fichaspuntuacion.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}
<br>
<br>
<style>
table{
  margin:auto;
  padding:15px;
  width:80%;
}
td{
  padding:5px;
  text-align:left;
}
tr{
  padding:10px
}

</style>


 

<h2> <int>Mejores productos</int></h2>



<br>

<table>

    {%for ficha in inventario_list %}
    <tr>    
        
    
    <td>CN: {{ficha.cn}}</td>   
    <td>Nombre: <a href="{%url 'fichaupdate' ficha.pk %}"><b>{{ficha.nombre}} </b></a></td> 
    <td>Zona: {{ficha.zonap}}</td>
    <td>PVP: {{ficha.pvp}}</td>   
    <td>PVF: {{ficha.pvf}}</td>
    <td>Puntuación:<b><id style="font-size: 13px; color:green;">{{ficha.media}}</id></b></td>   
    <td>Stock: {{ficha.stock}} </td> 
       
    <td><a href="{%url 'fichaupdate' ficha.id%}"title="Editar" ><i class="fa fa-edit"> </i></a></td>
        
        
     </tr>   
    {%endfor%}
</table>
<!-- Menú de paginación -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
</div>
</div>
</div>
</main>
{%endblock%}

Parapothek/fichas/templates/fichas/indicaciones.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}

<!--Submenu-->

<br>
<br>


<h2>Indicaciones</h2>
<br>
<a class='crearboton' style='color:rgb(14, 14, 13)' href="{% url 'indicacioncreate' %}"><i><b>Crear Nueva Indicación</b></i></a>
<br>
<br>
<div class="indicaciones">
    {%for indicacion in indicacion_list %}
     <div class="indicacion"   
        
    
        <h2><b>{{indicacion.nombre}}</b></h2>
        <div class='editarborrar'>
        <a href="{%url 'indicacionupdate' indicacion.id %}"title="Editar" ><i class="fa fa-edit"> </i></a><a href="{%url 'indicaciondelete' indicacion.id %}" title="Borrar"> <i class="fa fa-trash-o"></i></a></h5>
        </div> 
     </div>
    {%endfor%}

</div>
<br>
{%endblock%}

Parapothek/fichas/templates/fichas/zonasaplicacion.html
{%extends 'core/portada.html'%}
{% load static %}
{% block content %}

<!--Submenu-->




<br>
<br>
<br>
<br>


<h2> Zonas de Aplicación disponibles</h2>
<br>
<a class='crearboton' style='color:rgb(14, 14, 13)' href="{% url 'zonacreate' %}"><i><b>Crear Nueva Zona de Aplicación</b></i></a>
        
  <br>
  <div class="zonas">
    {%for zona in zona_list %}
        <div class="zona">
        
    
        <h5 ><b>{{zona.nombre}}</b></h5>
        <img src="{{zona.image.url}}"alt="{{zona.nombre}}"style="width:150px;height:100px;"></img>
        <br>
         <a href="{%url 'zonaupdate' zona.id %}"style="text-align:left;" title="Editar" ><i class="fa fa-edit"></i>  </a>
         |<a href="{%url 'zonadelete' zona.id %}"style="text-align:right;"title="Borrar"> <i class="fa fa-trash-o"></i></a>
        </div>
    {%endfor%}
  </div>

          
  
{%endblock%}